version: '3.8'

services:
  spreadsheet_client:
    build: 
      context: ./spreadsheet_client
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./spreadsheet_client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true